version: '3.8'

services:
  accounts-service:
    build:
      context: .
      dockerfile: apps/accounts-service/Dockerfile
    container_name: ledgerflow-accounts-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ledger_flow?schema=public
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  transactions-service:
    build:
      context: .
      dockerfile: apps/transactions-service/Dockerfile
    container_name: ledgerflow-transactions-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ledger_flow?schema=public
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  notification-service:
    build:
      context: .
      dockerfile: apps/notification-service/Dockerfile
    container_name: ledgerflow-notification-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ledger_flow?schema=public
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
